import { FormEvent, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ChevronRight, Heart, Menu, Search, ShoppingBag, Sparkles, Star, X } from "lucide-react";

export type Product = { slug: string; name: string; category: string; price: number; image: string; detail: string; badge?: string };

export const products: Product[] = [
  { slug: "signature-oval", name: "Signature Oval", category: "Branded Watches", price: 890, image: "/images/jewelluxe-classic-portrait.png", detail: "Gold-tone stainless steel / 32mm", badge: "New" },
  { slug: "luna-drop", name: "Luna Drop", category: "Jewelry", price: 340, image: "/images/jewelluxe-jewelry-detail.png", detail: "Gold vermeil / freshwater pearl" },
  { slug: "the-heirloom", name: "The Heirloom", category: "Exclusive Necklaces", price: 620, image: "/images/jewelluxe-hills-hero.png", detail: "18k gold / hand-set pendant", badge: "Bestseller" },
  { slug: "nocturne-heel", name: "Nocturne 90", category: "Women's Heels", price: 420, image: "https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1000", detail: "Satin black / leather sole" },
  { slug: "aurelia-watch", name: "Aurelia", category: "Branded Watches", price: 980, image: "https://images.pexels.com/photos/38946825/pexels-photo-38946825.jpeg?auto=compress&cs=tinysrgb&w=1000", detail: "Solar movement / champagne dial" },
  { slug: "arc-cuff", name: "Arc Cuff", category: "Jewelry", price: 280, image: "https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=1000", detail: "Recycled sterling silver" },
  { slug: "muse-sandal", name: "Muse Sandal", category: "Women's Heels", price: 365, image: "https://images.pexels.com/photos/1462637/pexels-photo-1462637.jpeg?auto=compress&cs=tinysrgb&w=1000", detail: "Ivory leather / 75mm heel" },
  { slug: "celeste-chain", name: "Celeste Chain", category: "Exclusive Necklaces", price: 490, image: "https://images.pexels.com/photos/10983783/pexels-photo-10983783.jpeg?auto=compress&cs=tinysrgb&w=1000", detail: "18k gold / 45cm" },
];

const categories = [
  ["Jewelry", "Quietly radiant", "/images/jewelluxe-jewelry-detail.png"],
  ["Women's Heels", "Walk your own line", "https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&w=1000"],
  ["Branded Watches", "Time, beautifully kept", "/images/jewelluxe-classic-portrait.png"],
  ["Exclusive Necklaces", "Make a lasting impression", "/images/jewelluxe-hills-hero.png"],
];

export default function Index() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [bag, setBag] = useState<Product[]>([]);
  const [liked, setLiked] = useState<string[]>([]);
  const [notice, setNotice] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const filtered = useMemo(() => query ? products.filter((p) => `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())) : [], [query]);
  const add = (product: Product) => { setBag((items) => [...items, product]); setNotice(`${product.name} added to your bag`); window.setTimeout(() => setNotice(""), 2400); };
  const scroll = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSubscribed(true); setNotice("Welcome to the Jewelluxe list"); window.setTimeout(() => setNotice(""), 2400); };
  return <main className="min-h-screen overflow-hidden bg-ink text-cream">
    <div className="flex min-h-9 items-center justify-center bg-gold px-4 py-2 text-center text-[10px] font-semibold uppercase tracking-[0.16em] text-ink">Complimentary shipping on orders over $150 · Complimentary returns</div>
    <header className="absolute left-0 right-0 top-9 z-30 border-b border-white/15 bg-ink/25 backdrop-blur-md"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 lg:px-10">
      <button onClick={() => scroll("top")} className="flex min-h-11 items-center gap-3 text-left" aria-label="Jewelluxe Co home"><span className="flex size-9 items-center justify-center border border-gold font-display text-2xl text-gold">J</span><span><strong className="block text-[11px] uppercase tracking-[0.28em]">Jewelluxe Co</strong><small className="mt-1 hidden text-[8px] uppercase tracking-[0.22em] text-cream/45 sm:block">Luxury essentials for her</small></span></button>
      <nav className="hidden items-center gap-7 text-[10px] font-semibold uppercase tracking-[0.2em] text-cream/75 md:flex"><button onClick={() => scroll("categories")}>Collections</button><button onClick={() => scroll("arrivals")}>New arrivals</button><button onClick={() => scroll("editorial")}>The journal</button><button onClick={() => scroll("about")}>About</button></nav>
      <div className="flex items-center gap-3"><button className="hidden min-h-11 min-w-11 items-center justify-center sm:flex" onClick={() => setSearchOpen((v) => !v)} aria-label="Search"><Search size={18} /></button><Link className="relative flex min-h-11 min-w-11 items-center justify-center" to="/account" aria-label="Account"><Heart size={18} /></Link><button className="relative flex min-h-11 min-w-11 items-center justify-center" onClick={() => scroll("arrivals")} aria-label="Shopping bag"><ShoppingBag size={18} />{bag.length > 0 && <span className="absolute right-0 top-0 flex size-4 items-center justify-center rounded-full bg-gold text-[9px] font-bold text-ink">{bag.length}</span>}</button><button className="flex min-h-11 min-w-11 items-center justify-center md:hidden" onClick={() => setMenuOpen((v) => !v)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div>
    </div>{searchOpen && <div className="border-t border-white/10 bg-ink px-5 py-4"><div className="mx-auto flex max-w-[1440px] items-center gap-3"><Search size={16} /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent py-2 text-base outline-none" placeholder="Search jewelry, heels, watches..." /></div>{query && <div className="mx-auto max-w-[1440px] pt-2 text-xs text-gold">{filtered.length} pieces found</div>}</div>}{menuOpen && <nav className="flex flex-col gap-2 border-t border-white/10 bg-ink px-5 py-5 text-[11px] uppercase tracking-[0.2em] md:hidden">{[["Collections", "categories"], ["New arrivals", "arrivals"], ["The journal", "editorial"], ["About", "about"]].map(([label, id]) => <button key={id} onClick={() => scroll(id)} className="min-h-11 text-left">{label}</button>)}</nav>}</header>

    <section id="top" className="relative flex min-h-[760px] items-end bg-ink pb-16 pt-44 lg:min-h-[900px] lg:pb-24"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(29,27,24,.95),rgba(29,27,24,.15)),linear-gradient(0deg,rgba(29,27,24,1),transparent_60%)]" /><div className="absolute right-0 top-0 h-full w-full bg-cover bg-center opacity-75 sm:w-[70%]" style={{ backgroundImage: "url(/images/jewelluxe-hills-hero.png)" }} /><div className="relative mx-auto w-full max-w-[1440px] px-5 lg:px-10"><div className="max-w-3xl"><p className="mb-8 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.28em] text-gold"><Sparkles size={14} /> The new Jewelluxe edit</p><h1 className="font-display text-[clamp(4.3rem,10vw,9rem)] leading-[.82] tracking-[-.07em]">Made to be<br /><em className="font-editorial font-normal text-gold">noticed.</em></h1><p className="mt-9 max-w-sm text-sm leading-6 text-cream/65">Curated jewelry, heels and watches for women who define their own style.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => scroll("arrivals")} className="flex min-h-12 items-center justify-center gap-3 bg-gold px-6 text-[10px] font-bold uppercase tracking-[.18em] text-ink">Shop collection <ArrowRight size={15} /></button><button onClick={() => scroll("categories")} className="flex min-h-12 items-center justify-center border border-cream/35 px-6 text-[10px] font-bold uppercase tracking-[.18em]">Explore categories</button></div></div></div><div className="absolute bottom-8 right-5 hidden text-right text-[9px] uppercase tracking-[.22em] text-cream/45 lg:block">01 / 04<br /><span className="text-gold">Classic, never ordinary</span></div></section>
    <section id="categories" className="bg-cream px-5 py-16 text-ink lg:px-10 lg:py-24"><div className="mx-auto max-w-[1440px]"><div className="mb-10 flex items-end justify-between gap-5"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.25em] text-gold">Shop by mood</p><h2 className="font-display text-4xl tracking-[-.05em] sm:text-6xl">Find your signature.</h2></div><span className="hidden text-[10px] uppercase tracking-[.2em] text-ink/45 sm:block">Curated for every version of her</span></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{categories.map(([name, tagline, image]) => <button key={name} onClick={() => scroll("arrivals")} className="group relative aspect-[.75] overflow-hidden bg-ink text-left text-cream"><img src={image} alt={name} className="h-full w-full object-cover opacity-75 transition duration-700 group-hover:scale-105 group-hover:opacity-90" /><div className="absolute inset-0 bg-gradient-to-t from-ink/90 to-transparent" /><div className="absolute bottom-5 left-4 right-4"><p className="font-display text-2xl leading-none sm:text-3xl">{name}</p><p className="mt-2 text-[9px] uppercase tracking-[.16em] text-cream/60">{tagline}</p></div></button>)}</div></div></section>
    <section id="arrivals" className="bg-ink px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="mb-10 flex items-end justify-between border-b border-white/10 pb-6"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.25em] text-gold">01 / New arrivals</p><h2 className="font-display text-5xl tracking-[-.05em] sm:text-6xl">The latest edit.</h2></div><Link to="/collection/new-arrivals" className="hidden min-h-11 items-center gap-2 text-[10px] uppercase tracking-[.18em] text-gold sm:flex">View all <ChevronRight size={14} /></Link></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-3 lg:grid-cols-4">{products.slice(0, 4).map((p) => <ProductCard key={p.slug} product={p} liked={liked.includes(p.slug)} onLike={() => setLiked((v) => v.includes(p.slug) ? v.filter((x) => x !== p.slug) : [...v, p.slug])} onAdd={() => add(p)} />)}</div></div></section>
    <section id="editorial" className="grid bg-gold text-ink lg:grid-cols-2"><div className="min-h-[420px] bg-cover bg-center" style={{ backgroundImage: "url(/images/jewelluxe-classic-portrait.png)" }} /><div className="flex flex-col justify-center px-5 py-16 lg:px-16"><p className="mb-5 text-[10px] font-bold uppercase tracking-[.25em]">The Jewelluxe journal</p><h2 className="max-w-lg font-display text-5xl leading-[.9] tracking-[-.06em] sm:text-7xl">The art of<br /><em className="font-editorial font-normal">the finishing touch.</em></h2><p className="mt-7 max-w-md text-base leading-7">Style is rarely one grand gesture. It is the watch at your wrist, the heel that changes your posture, the necklace that catches the light when you turn.</p><button onClick={() => scroll("arrivals")} className="mt-8 flex min-h-11 items-center gap-3 self-start border-b border-ink pb-2 text-[10px] font-bold uppercase tracking-[.18em]">Read the journal <ArrowRight size={15} /></button></div></section>
    <section id="about" className="bg-ink-soft px-5 py-16 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.25em] text-gold">Why Jewelluxe</p><h2 className="font-display text-5xl leading-[.9] tracking-[-.06em] sm:text-7xl">Luxury with<br /><em className="font-editorial font-normal text-gold">intention.</em></h2></div><div className="grid gap-8 sm:grid-cols-3"><Insight title="01" text="Considered pieces designed to live beyond the occasion." /><Insight title="18k" text="Materials chosen for a lifetime of wear and memory." /><Insight title="∞" text="Personal style is never finished. Keep discovering." /></div></div></section>
    <section className="bg-cream px-5 py-16 text-ink lg:px-10 lg:py-24"><div className="mx-auto max-w-[1440px] text-center"><p className="mb-4 text-[10px] font-bold uppercase tracking-[.25em] text-gold">Loved by women who know</p><div className="mx-auto flex max-w-3xl justify-center gap-1 text-gold">{Array.from({ length: 5 }).map((_, i) => <Star key={i} fill="currentColor" size={16} />)}</div><blockquote className="mx-auto mt-6 max-w-3xl font-display text-3xl leading-tight sm:text-5xl">“The kind of pieces that make getting dressed feel like a ritual.”</blockquote><p className="mt-5 text-[10px] font-bold uppercase tracking-[.2em] text-ink/45">— Maya R., verified customer</p></div></section>
    <footer className="border-t border-white/10 bg-ink px-5 py-14 lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 md:grid-cols-[1.4fr_1fr_1fr_1.2fr]"><div><p className="font-display text-3xl text-gold">Jewelluxe Co</p><p className="mt-4 max-w-xs text-sm leading-6 text-cream/50">Luxury essentials for women who define their own style.</p></div><Footer title="Shop" links={["New arrivals", "Jewelry", "Women's heels", "Watches"]} /><Footer title="Client care" links={["Shipping & returns", "Size guide", "Contact us", "Track order"]} /><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.2em] text-cream/45">Join the list</p>{subscribed ? <p className="text-sm text-gold">You are on the list.</p> : <form onSubmit={submit} className="flex border-b border-cream/25"><input required type="email" aria-label="Email address" placeholder="Email address" className="w-full bg-transparent py-3 text-base outline-none placeholder:text-cream/35" /><button className="min-h-11 text-gold" aria-label="Subscribe"><ArrowRight size={16} /></button></form>}</div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/10 pt-5 text-[9px] uppercase tracking-[.18em] text-cream/35 sm:flex-row sm:justify-between"><span>© 2026 Jewelluxe Co</span><Link to="/admin">Admin portal</Link><span>New York · London · Everywhere</span></div></div></footer>
    {notice && <div role="status" aria-live="polite" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-gold px-5 py-3 text-[10px] font-bold uppercase tracking-[.15em] text-ink shadow-2xl">{notice}</div>}
  </main>;
}

function ProductCard({ product, liked, onLike, onAdd }: { product: Product; liked: boolean; onLike: () => void; onAdd: () => void }) { return <article className="group"><Link to={`/product/${product.slug}`} className="relative block aspect-[.82] overflow-hidden bg-cream/5"><img src={product.image} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />{product.badge && <span className="absolute left-3 top-3 bg-gold px-2 py-1 text-[8px] font-bold uppercase tracking-[.15em] text-ink">{product.badge}</span>}</Link><div className="pt-4"><div className="flex justify-between gap-2"><Link to={`/product/${product.slug}`} className="font-display text-xl tracking-[-.03em] text-cream sm:text-2xl">{product.name}</Link><button onClick={onLike} aria-label={`Wishlist ${product.name}`} className={liked ? "text-gold" : "text-cream/50"}><Heart size={16} fill={liked ? "currentColor" : "none"} /></button></div><p className="mt-1 text-[10px] uppercase tracking-[.13em] text-cream/45">{product.detail}</p><div className="mt-3 flex items-center justify-between"><span className="text-sm text-gold">${product.price}</span><button onClick={onAdd} className="min-h-11 text-[9px] font-bold uppercase tracking-[.15em] text-cream/70 hover:text-gold">Add to bag</button></div></div></article>; }
function Insight({ title, text }: { title: string; text: string }) { return <div className="border-l border-gold/60 pl-4"><p className="font-display text-3xl text-cream">{title}</p><p className="mt-2 text-xs leading-5 text-cream/50">{text}</p></div>; }
function Footer({ title, links }: { title: string; links: string[] }) { return <div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.2em] text-cream/45">{title}</p><div className="flex flex-col gap-1">{links.map((link) => <button key={link} className="min-h-11 text-left text-sm text-cream/65 hover:text-gold">{link}</button>)}</div></div>; }
